## NUMPY

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [6]:
a[1][2]

7

In [7]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [8]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
list(range(5))

[0, 1, 2, 3, 4]

In [12]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [13]:
a_list = list(range(10))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
a_list.append(list(range(3)))

In [15]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2]]

In [16]:
for i in range(3):
    a_list.append(i)

print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2], 0, 1, 2]


In [17]:
np.append(range(10), range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [18]:
a_numpy = np.arange(10)
a_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
np.append(a_numpy, range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [21]:
np.append(a_numpy, np.arange(6).reshape(3,2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [22]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [7, 8, 9]], axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [24]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.array([7, 8, 9])

array([7, 8, 9])

In [26]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9, 10]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
axis=0 baris
axis=1 kolom

SyntaxError: invalid syntax (118056180.py, line 1)

In [30]:
np.delete(a, -1, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
b_sort = np.append(range(52,55), range(21,27))

In [32]:
np.sort(b_sort)

array([21, 22, 23, 24, 25, 26, 52, 53, 54])

In [33]:
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12


In [34]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
[:, newaxis]

In [37]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [39]:
a

array([0, 1, 2, 3, 4])

In [40]:
np.expand_dims(a, axis=1).shape

(5, 1)

## INDEXING SLICING

In [41]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [42]:
a[0]

0

In [43]:
a[0:3]

array([0, 1, 2])

In [44]:
a[:3]

array([0, 1, 2])

In [45]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [46]:
a[-3:]

array([3, 4, 5])

In [47]:
a[:-1]

array([0, 1, 2, 3, 4])

In [48]:
a > 2

array([False, False, False,  True,  True,  True])

In [49]:
a[np.array([False, False, True,  True, False,   True])]

array([2, 3, 5])

In [50]:
a[a > 2]

array([3, 4, 5])

In [51]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [53]:
above_five = a > 8

In [54]:
a[above_five]

array([ 9, 10, 11])

In [ ]:
True False

In [ ]:
==
>=
<=
>
<

In [55]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [56]:
a_list * 2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [0, 1, 2],
 0,
 1,
 2,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 [0, 1, 2],
 0,
 1,
 2]

In [57]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [58]:
genap = a % 2 == 0

a[genap]

array([ 0,  2,  4,  6,  8, 10])

In [59]:
a[(a > 2) & (a < 11) & (a % 2 != 0)]

array([3, 5, 7, 9])

In [60]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a_1 = np.append([[1, 1]], [[2, 2]], axis=0)

In [62]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

In [63]:
np.append(a_1, a_2, axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [65]:
np.append(a_1, a_2, axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [66]:
np.vstack([a_1, a_2])  # append axis 0

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack([a_1, a_2])  # append axis 1

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [68]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [70]:
tuple(range(10, 100, 5))

(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95)

In [71]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [72]:
h_1, h_2, h_3 = np.hsplit(arrsplit, 3)

In [73]:
np.hstack([h_1, h_2, h_3])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [74]:
h_1

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [75]:
h_2

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [76]:
arrsplit.shape

(2, 12)

In [77]:
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [78]:
np.hsplit(arrsplit, 10)

ValueError: array split does not result in an equal division

In [79]:
b = a

In [80]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
b[1][-1] = 100

In [83]:
b

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [84]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [85]:
id(a)

1779578824048

In [86]:
id(b)

1779578824048

In [87]:
id(a) == id(b)

True

In [88]:
object -> a -> b

SyntaxError: invalid syntax (2248001338.py, line 1)

In [89]:
print(id(a))
print(id(a.view()))

1779578824048
1779578639536


In [90]:
print(id(a))
print(id(a.view()))

1779578824048
1779579004560


In [92]:
c = a.view()

In [93]:
print(id(a))
print(id(c))

1779578824048
1779578564112


In [94]:
id(a.copy())

1779578758704

In [95]:
id(a)

1779578824048

In [96]:
dataframe
backup_dataframe = dataframe.copy()

NameError: name 'dataframe' is not defined

In [97]:
dataframe = backup_dataframe.copy()

NameError: name 'backup_dataframe' is not defined

## BASIC OPERATION

In [ ]:
+
-
/
*
%

In [98]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [99]:
a + 5

array([[  5,   6,   7,   8],
       [  9,  10,  11, 105],
       [ 13,  14,  15,  16]])

In [100]:
a - 5

array([[-5, -4, -3, -2],
       [-1,  0,  1, 95],
       [ 3,  4,  5,  6]])

In [101]:
a * 3

array([[  0,   3,   6,   9],
       [ 12,  15,  18, 300],
       [ 24,  27,  30,  33]])

In [102]:
a / 3

array([[ 0.        ,  0.33333333,  0.66666667,  1.        ],
       [ 1.33333333,  1.66666667,  2.        , 33.33333333],
       [ 2.66666667,  3.        ,  3.33333333,  3.66666667]])

In [103]:
a % 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]], dtype=int32)

In [104]:
a + 5 - 7 * 3

array([[-16, -15, -14, -13],
       [-12, -11, -10,  84],
       [ -8,  -7,  -6,  -5]])

In [105]:
a + a

array([[  0,   2,   4,   6],
       [  8,  10,  12, 200],
       [ 16,  18,  20,  22]])

In [106]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [107]:
np.ones(12).reshape(3, 4)  * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [108]:
a * np.ones(12).reshape(3, 4) * 3

array([[  0.,   3.,   6.,   9.],
       [ 12.,  15.,  18., 300.],
       [ 24.,  27.,  30.,  33.]])

In [ ]:
a b    x    a  b
c d         c  d

In [ ]:
a*a + b*c        a*b + b*d
c*a + d*c        c*b + d*d

In [ ]:
np.dot

In [109]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [110]:
np.arange(5).sum()

10

In [111]:
np.sum(np.arange(5))

10

In [112]:
a.sum()  # method call

159

In [113]:
np.sum(a)  # function call

159

In [114]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [115]:
np.nan

nan

In [ ]:
not a number

In [ ]:
null

In [ ]:
np.sum()
np.absolute()
np.mean()
np.median()
np.add()
np.subtract()
np.nansum()

In [117]:
np.array([np.nan, 5]).sum()

nan

In [118]:
np.nansum(np.array([np.nan, 5]))

5.0

In [119]:
np.linspace(1, 4, num=4).reshape(2, 2)

array([[1., 2.],
       [3., 4.]])

In [120]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [121]:
np.linspace(1, 4, num=4).reshape(2, 2).dot(np.identity(2))

array([[1., 2.],
       [3., 4.]])

In [122]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [123]:
b.sum(axis=1)

array([2, 4])

In [124]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [125]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [126]:
x1 = np.linspace(5, 122, num=4).reshape(2, 2)
x2 = np.linspace(8, 32, num=4).reshape(2, 2)

In [127]:
x1

array([[  5.,  44.],
       [ 83., 122.]])

In [128]:
x2

array([[ 8., 16.],
       [24., 32.]])

In [129]:
x1 * x2

array([[  40.,  704.],
       [1992., 3904.]])

In [130]:
np.product([x1, x2], axis=1)

array([[ 415., 5368.],
       [ 192.,  512.]])

In [131]:
np.maximum(x1, x2)

array([[  8.,  44.],
       [ 83., 122.]])

In [132]:
np.minimum(x1, x2)

array([[ 5., 16.],
       [24., 32.]])

In [133]:
np.std([x1, x2], axis=0)

array([[ 1.5, 14. ],
       [29.5, 45. ]])

In [134]:
np.min(x2)

8.0

In [135]:
np.random.randint(1, 100, size=10)

array([23, 99, 67, 96,  5, 69, 72, 22, 67, 82])

In [136]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [137]:
np.random.randn(3, 4)

array([[-2.1148827 , -1.99171395,  2.29702824,  0.21050196],
       [ 0.32119114, -0.18481353, -0.6278247 ,  3.08039751],
       [-0.39587358,  0.39686385,  0.15285832,  0.59840811]])

In [138]:
d = np.random.randn(4, 3)

In [139]:
a * d

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
(4,3)(3,4)

In [140]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [141]:
d

array([[ 1.87293373, -0.35604408,  0.11395873],
       [ 1.77043922,  0.18026657,  0.26188854],
       [ 0.51153675, -0.08374984, -1.2584773 ],
       [ 1.42274648,  0.44424688,  0.22619212]])

In [142]:
a @ d

array([[  7.06175216,   1.34550752,  -1.57648969],
       [161.68779945,  43.39934503,  16.83362593],
       [ 51.6830016 ,   2.82326373,  -6.827993  ]])

In [143]:
d @ a

array([[ -0.51250652,   1.11834186,   2.74919023, -28.73206087],
       [  2.81617455,   5.02876887,   7.24136319,  26.21874819],
       [-10.40281771, -11.23350809, -12.06419847, -20.68362351],
       [  3.58652447,   5.67970995,   7.77289542,  51.1810403 ]])

In [144]:
a.dot(d)

array([[  7.06175216,   1.34550752,  -1.57648969],
       [161.68779945,  43.39934503,  16.83362593],
       [ 51.6830016 ,   2.82326373,  -6.827993  ]])

In [145]:
np.dot(a, d)

array([[  7.06175216,   1.34550752,  -1.57648969],
       [161.68779945,  43.39934503,  16.83362593],
       [ 51.6830016 ,   2.82326373,  -6.827993  ]])

In [146]:
d[1:3, 1]

array([ 0.18026657, -0.08374984])

In [147]:
d[baris, kolom]

NameError: name 'baris' is not defined

In [148]:
d

array([[ 1.87293373, -0.35604408,  0.11395873],
       [ 1.77043922,  0.18026657,  0.26188854],
       [ 0.51153675, -0.08374984, -1.2584773 ],
       [ 1.42274648,  0.44424688,  0.22619212]])

In [149]:
d[1:3, 0:2]

array([[ 1.77043922,  0.18026657],
       [ 0.51153675, -0.08374984]])

In [150]:
d

array([[ 1.87293373, -0.35604408,  0.11395873],
       [ 1.77043922,  0.18026657,  0.26188854],
       [ 0.51153675, -0.08374984, -1.2584773 ],
       [ 1.42274648,  0.44424688,  0.22619212]])

In [151]:
d.T

array([[ 1.87293373,  1.77043922,  0.51153675,  1.42274648],
       [-0.35604408,  0.18026657, -0.08374984,  0.44424688],
       [ 0.11395873,  0.26188854, -1.2584773 ,  0.22619212]])

In [152]:
d.transpose()

array([[ 1.87293373,  1.77043922,  0.51153675,  1.42274648],
       [-0.35604408,  0.18026657, -0.08374984,  0.44424688],
       [ 0.11395873,  0.26188854, -1.2584773 ,  0.22619212]])

In [153]:
np.transpose(d)

array([[ 1.87293373,  1.77043922,  0.51153675,  1.42274648],
       [-0.35604408,  0.18026657, -0.08374984,  0.44424688],
       [ 0.11395873,  0.26188854, -1.2584773 ,  0.22619212]])

In [154]:
d.reshape(3, 4)

array([[ 1.87293373, -0.35604408,  0.11395873,  1.77043922],
       [ 0.18026657,  0.26188854,  0.51153675, -0.08374984],
       [-1.2584773 ,  1.42274648,  0.44424688,  0.22619212]])

In [155]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [156]:
ndarr.ndim

3

In [157]:
ndarr.shape

(2, 2, 2)

In [158]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [159]:
ndarr.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
ndarr.flatten().reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))